printf ""
printf "\n   /gg\           /gg\ "
printf "\n  /g.gg\         /gg.g\ "
printf "\n |gg..gg\       /gg..gg| "
printf "\n |gg...g|       |g...gg| "
printf "\n |gg...g|       |g...gg| "
printf "\n  \gg..g/       \g..gg/ "
printf "\n   |gg.gvgggggggvg.gg| "
printf "\n  /ggggggggggggggggggg\ "
printf "\n /gggg(((ggggggg)))gggg\ "
printf "\n|ggggg....ggggg....ggggg| "
printf "\n|ggggg....ggggg....ggggg| "
printf "\n|ggcccgggg\___/ggggcccgg| "
printf "\n|ggcccccgggg|ggggcccccgg| "
printf "\n  \gcccggg\---/gggcccg/ "
printf "\n     \ggggggggggggg/"
printf ""
